#!/usr/bin/env python3
"""Generate Markdown report from retrieval/rerank experiment results."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate retrieval experiment markdown report.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--input",
        default="output/retrieval_eval_results.json",
        help="Experiment result JSON path generated by eval_retrieval_rerank.py",
    )
    parser.add_argument(
        "--output",
        default="output/retrieval_experiment_report.md",
        help="Markdown report output path",
    )
    return parser.parse_args()


def load_payload(path: str) -> dict[str, Any]:
    target = Path(path)
    if not target.exists():
        raise FileNotFoundError(f"Result JSON not found: {target}")
    return json.loads(target.read_text(encoding="utf-8-sig"))


def to_markdown_table(rows: list[dict[str, Any]]) -> str:
    header = (
        "| Retrieval | Rerank | Enhancer | Recall@K | MRR@K | nDCG@K | "
        "Latency Avg (ms) | Latency P95 (ms) |\n"
        "|---|---|---|---:|---:|---:|---:|---:|"
    )
    body_lines: list[str] = []
    for item in rows:
        body_lines.append(
            "| "
            f"{item['retrieval']} | {item['rerank']} | {item['enhancer']} | "
            f"{item['recall_at_k']:.4f} | {item['mrr_at_k']:.4f} | {item['ndcg_at_k']:.4f} | "
            f"{item['latency_ms_avg']:.2f} | {item['latency_ms_p95']:.2f} |"
        )
    return "\n".join([header, *body_lines])


def build_summary(payload: dict[str, Any]) -> str:
    results: list[dict[str, Any]] = list(payload["results"])
    best: dict[str, Any] = dict(payload["best"])
    config = payload["config"]

    baseline = None
    for item in results:
        if (
            item["retrieval"] == "bm25"
            and item["rerank"] == "none"
            and item["enhancer"] == "identity"
        ):
            baseline = item
            break

    if baseline is None:
        for item in results:
            if (
                item["retrieval"] == "dense"
                and item["rerank"] == "none"
                and item["enhancer"] == "identity"
            ):
                baseline = item
                break

    lines = [
        f"- 实验配置：{config['questions']} 个测试问题，Top-K={config['top_k']}",
        f"- 最优组合：`{best['retrieval']} + {best['rerank']} + {best['enhancer']}`",
        f"- 最优指标：Recall@K={best['recall_at_k']:.4f}, Precision@K={best['precision_at_k']:.4f}, "
        f"MRR@K={best['mrr_at_k']:.4f}, nDCG@K={best['ndcg_at_k']:.4f}, "
        f"平均延迟={best['latency_ms_avg']:.2f}ms (P95={best['latency_ms_p95']:.2f}ms)",
    ]
    
    if baseline is not None:
        recall_gain = best["recall_at_k"] - baseline["recall_at_k"]
        precision_gain = best["precision_at_k"] - baseline["precision_at_k"]
        mrr_gain = best["mrr_at_k"] - baseline["mrr_at_k"]
        ndcg_gain = best["ndcg_at_k"] - baseline["ndcg_at_k"]
        latency_ratio = best["latency_ms_avg"] / baseline["latency_ms_avg"] if baseline["latency_ms_avg"] > 0 else float('inf')
        
        lines.append("")
        lines.append(f"- **Baseline** (`{baseline['retrieval']} + {baseline['rerank']} + {baseline['enhancer']}`):")
        lines.append(f"  - Recall@K={baseline['recall_at_k']:.4f}, Precision@K={baseline['precision_at_k']:.4f}")
        lines.append(f"  - MRR@K={baseline['mrr_at_k']:.4f}, nDCG@K={baseline['ndcg_at_k']:.4f}")
        lines.append(f"  - 延迟={baseline['latency_ms_avg']:.2f}ms")
        lines.append("")
        lines.append("- **增益对比**（最优 vs Baseline）：")
        lines.append(f"  - Recall@K: {'+' if recall_gain >= 0 else ''}{recall_gain:.4f} ({recall_gain*100:.1f}%)")
        lines.append(f"  - Precision@K: {'+' if precision_gain >= 0 else ''}{precision_gain:.4f} ({precision_gain*100:.1f}%)")
        lines.append(f"  - MRR@K: {'+' if mrr_gain >= 0 else ''}{mrr_gain:.4f} ({mrr_gain*100:.1f}%)")
        lines.append(f"  - nDCG@K: {'+' if ndcg_gain >= 0 else ''}{ndcg_gain:.4f} ({ndcg_gain*100:.1f}%)")
        lines.append(f"  - 延迟变化: {latency_ratio:.2f}x")

    return "\n".join(lines)


def generate_markdown(payload: dict[str, Any]) -> str:
    config = payload["config"]
    results: list[dict[str, Any]] = list(payload["results"])
    best = payload["best"]
    table = to_markdown_table(results)
    summary = build_summary(payload)

    return f"""# BigR Retrieval Enhancement Experiment Report

## 1. 实验目标
- 评估 Query Enhancement、Retrieval 策略、Rerank 策略对检索质量与延迟的影响。
- 支撑检索层 ablation study：明确各模块的独立贡献与组合收益。

## 2. 系统结构图
```mermaid
flowchart LR
    Q[User Query] --> QE[Query Enhancer]
    QE --> R[Retriever dense/bm25/hybrid]
    R --> M[Merge / Candidate Pool]
    M --> RR[Reranker none/keyword/cross_encoder]
    RR --> O[Top-K Results]
    O --> E[Offline Metrics: Recall MRR nDCG Latency]
```

## 3. Query Enhancement 方法
- `identity`: 原始查询，不做改写。
- `rewrite`: LLM 输出一个优化检索表达。
- `expansion`: LLM 输出多个改写/子查询用于 multi-query 检索。

## 4. Retrieval Strategies
- `dense`: 向量相似度检索。
- `bm25`: 稀疏词法检索（项目内映射到 `sparse`）。
- `hybrid`: dense + sparse 融合检索。

## 5. Rerank Strategies
- `none`: 不重排，作为 baseline。
- `keyword`: 关键词重排器。
- `cross_encoder`: 交叉编码器重排。

## 6. 实验设计矩阵（3D）
- Retrieval: {", ".join(config["retrieval_methods"])}
- Rerank: {", ".join(config["rerank_methods"])}
- QueryEnhancer: {", ".join(config["enhancers"])}
- 问题数: {config["questions"]}
- Top-K: {config["top_k"]}
- 相关性阈值（overlap）: {config["min_overlap"]}

总组合数：`{len(config["retrieval_methods"])} × {len(config["rerank_methods"])} × {len(config["enhancers"])} = {len(results)}`

## 7. 指标定义
- `Recall@K`: Top-K 内是否检索到至少一个相关文档（实验中按问题平均）。
- `MRR@K`: 第一个相关文档倒数排名的均值。
- `nDCG@K`: 基于相关性分值的归一化折损累计增益。
- `latency`: 单问题耗时（含查询增强、检索、重排）。

## 8. 实验结果表
{table}

## 9. 初步结论（自动生成）
{summary}

---
_本报告由 `scripts/generate_retrieval_report.py` 自动生成，支持重复运行覆盖更新。_
"""


def main() -> None:
    args = parse_args()
    payload = load_payload(args.input)
    markdown = generate_markdown(payload)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    print(f"[SAVE] Markdown report: {output}")


if __name__ == "__main__":
    main()
